- name: My Playbook
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars_prompt:
    - name: "ansible_become_password"
      prompt: "Enter your sudo password"
      private: true
  tasks:
    - name: Install nginx on Fedora
      dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
