- name: Create directory
  hosts: all
  gather_facts: true
  become: false
  tasks:
    - name: Create directory in home
      file:
        path: "~/spotify"
        state: directory
        mode: "0755"

# Create a new directory in host VM with name spotify in homw directory