- name: My Playbook
  hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_user: root
    ansible_password: admin!@1234
  tasks:
    - name: Install nginx on Fedora
      dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
