- name: My Playbook
  hosts: all
  gather_facts: true
  become: false
  tasks:
    - name: Install nginx on Fedora
      dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
